### PR TITLE
Homework3 - updated Hw3 files

### PR DESCRIPTION
**Pull request by KSKRLIFE**
Updated from feedback

### CODE REVIEW

**Review by rohan-singh1 — COMMENTED** [review]
Hey man, there are errors in Exercise 01; the browser shows an error in the following links:
- /cookie
- /check-cookies
- /other

Also, in Exercise 03, visiting the URL doesn't load anything. The user has to explicitly add /form to access the form. You could consider adding a redirect from / to /form.

I really liked the clean way with which you implemented Exercise 02.

**Comment by KSKRLIFE** [comment]
> Hey man, there are errors in Exercise 01; the browser shows an error in the following links:
> 
> * /cookie
> * /check-cookies
> * /other
> 
> Also, in Exercise 03, visiting the URL doesn't load anything. The user has to explicitly add /form to access the form. You could consider adding a redirect from / to /form.
> 
> I really liked the clean way with which you implemented Exercise 02.

Hi Rohan,

Thank you for your time in reviewing this, I just tried Exercise 1 and /cache, /check-cookies and /other are woking fine
in my browser. Port number was 5002 in the code and I changed it now, That might have caused the issue?

Thanks for pointing out on exercise 3, I just modified it to redirect to /form.

**Comment by TimmyYoung** [comment]
I ran each exercise after your most recent revisions. I did not encounter any bugs, it looks like your recent fixes must have worked!
I thought exercise #3 was missing something, but I did not read the homework guide clearly enough. The example shows comments and a newsletter submission box, but I don't think this was explicitly necessary.

In terms of code style/formatting, you were able to approach the solution without excessive amounts of code! Major refactoring is not really needed, but some of the spacing in exercises 2,3 is not consistent. This isn't a big deal really with the amount of code to read/review. It does make your code for exercise 3 harder to read, especially after following an if/else statement. The reviewer really has to step through the code slowly to find closing braces/brackets as well as statement control flow. 

Overall great job on getting those bugs fixed and the assignment!

**Review by TimmyYoung — APPROVED** [review]
I ran each exercise after your most recent revisions. I did not encounter any bugs, it looks like your recent fixes must have worked!
I thought exercise https://github.com/KSKRLIFE/student-repo-fullstack/pull/3 was missing something, but I did not read the homework guide clearly enough. The example shows comments and a newsletter submission box, but I don't think this was explicitly necessary.

In terms of code style/formatting, you were able to approach the solution without excessive amounts of code! Major refactoring is not really needed, but some of the spacing in exercises 2,3 is not consistent. This isn't a big deal really with the amount of code to read/review. It does make your code for exercise 3 harder to read, especially after following an if/else statement. The reviewer really has to step through the code slowly to find closing braces/brackets as well as statement control flow.

Overall great job on getting those bugs fixed and the assignment!

**Comment by JeremyIV** [comment]
Ex1: Looks good!

Ex2: Looks good!

Ex3: you are missing the feedback textarea and newsletter checkbox. Also, this javascript file is not consistently formatted. Otherwise, looks ok.

**Pull request merged**
