### PR TITLE
HW2

### PR DESCRIPTION
**Pull request by KSKRLIFE**
Added updated Home work 2 files.

### CODE REVIEW

**Comment by mahlpdx** [comment]
Hey Sai,

A few notes:

1. On exercise 1, it appears that you are missing a variable for nickel (5 cents). While your code passes the given test cases, it wouldn't accurately output change for something like $1.15. 
2. Exercise 2 looks great. The code is very straightforward and concisely accomplishes the task at hand.
3. In exercise 3, you don't have any checks to ensure that name and email are inputted. As it currently stands, your code will simply log an empty string if name and email aren't inputted instead of alerting the user that it is a required field. I also think code readability could be improved with more descriptive variable names (instead of a, b, c).
4. Exercise 4 is clear, but I'm unsure if the code as it stands will output the countries in alphabetical order (as seen in the homework description). Currently is looping through the data as it's received from the API, which is not in alphabetical order. Applying a sorting algorithm before your main loop can remedy this. 

Overall, great job on this assignment! All of your code was easy to read and well formatted.

**Comment by KSKRLIFE** [comment]
> Hey Sai,
> 
> A few notes:
> 
> 1. On exercise 1, it appears that you are missing a variable for nickel (5 cents). While your code passes the given test cases, it wouldn't accurately output change for something like $1.15.
> 2. Exercise 2 looks great. The code is very straightforward and concisely accomplishes the task at hand.
> 3. In exercise 3, you don't have any checks to ensure that name and email are inputted. As it currently stands, your code will simply log an empty string if name and email aren't inputted instead of alerting the user that it is a required field. I also think code readability could be improved with more descriptive variable names (instead of a, b, c).
> 4. Exercise 4 is clear, but I'm unsure if the code as it stands will output the countries in alphabetical order (as seen in the homework description). Currently is looping through the data as it's received from the API, which is not in alphabetical order. Applying a sorting algorithm before your main loop can remedy this.
> 
> Overall, great job on this assignment! All of your code was easy to read and well formatted.

Hi Drew, Thank you so much for your time and feedback on this. Will work on these.

**Review by rohan-singh1 — COMMENTED** [review]
Dude, code for questions 1,3 and 4 just won't work. I think you have some incorrect merges because I can see the Git additions to your code, like "<<<<<<< HEAD" and ">>>>>>> 845f736f84a11346e07d1b694f1008bfe268cde5".

I think you should remove these and then commit the changes so that your code can run successfully.

Rest of the code is quite good!

**Comment by KSKRLIFE** [comment]
> Dude, code for questions 1,3 and 4 just won't work. I think you have some incorrect merges because I can see the Git additions to your code, like "<<<<<<< HEAD" and ">>>>>>> [845f736](https://github.com/KSKRLIFE/student-repo-fullstack/commit/845f736f84a11346e07d1b694f1008bfe268cde5)".
> 
> I think you should remove these and then commit the changes so that your code can run successfully.
> 
> Rest of the code is quite good!

Hi Rohan,

I updated a few things in the second commit and there were some conflicts, so looks like that's messed.
Thank you.

**Comment by Al1999** [comment]
Hi Sai, 

It seems that there are some merge conflicts in your code. You should be able to solve this issue by choosing which change should be used in the code. Other than that, you have done a good job!

Thank you for sharing!
Al

**Pull request merged**
